[package]
name = "tilemap"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lerp = "0.4"
num = "0.4"

[dev-dependencies]
approx = "0.5"
